export const GET_SONG_DATA = "GET_SONG_DATA";
export const GET_ARTIST_DATA = "GET_ARTIST_DATA";
export const RECEIVE_SONG_DATA = "RECEIVE_SONG_DATA";
export const RECEIVE_ARTIST_DATA = "RECEIVE_ARTIST_DATA";
export const RECEIVE_LYRIC_DATA = "RECEIVE_LYRIC_DATA";
export const RECEIVE_ERROR = "RECIEVE_ERROR";